name: Test Application (e2e)

on:
  pull_request:
    branches:
      - main
      - fix-ci
  workflow_dispatch:

jobs:
  tests:
    name: cypress
    runs-on: ubuntu-20.04
    concurrency: ci-test
    timeout-minutes: 50
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install deps
        run: npm install

      - name: Setting up for local test
        run: make setup-test

      - name: Run Locally
        run: make run-test

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on-timeout: 200
          wait-on: 'http://localhost:3000/retailer'
          record: true
        env:
          CYPRESS_RECORD_KEY: 'dfd568c1-3ec9-4d1e-a647-8e547b680443'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
